language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.4.0
  - 2.4.1
  - ruby-head
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - "gem update --system"
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rspec
  - bundle exec rubocop
